version: 0.0
os: linux

files:
  - source: /avsapp/target/avs-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/avsapp

hooks:
  BeforeInstall:
    - location: ./avsapp/codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: ./avsapp/codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./avsapp/codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu